apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mnist-model
spec:
  predictor:
    pytorch:
      storageUri: "s3://mnist-models/mnist_model.pt"
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: AWS_SECRET_ACCESS_KEY
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"

